version: "3"

services:
  database:
    image: "postgres:latest"

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: medi_agenda

    volumes:
      - ./db-data/:/var/lib/postgresql/data/

    restart: always
